### ISSUE TITLE
problem using private key authentication

### ISSUE THREAD

**Issue by wkerzendorf** [SchoofsKelvin/vscode-sshfs#102]
My config used to work and as of yesterday evening I get the following error

`Error while connecting to SSH FS XXXX: Cannot parse privateKey: Passphrase must be a string or Buffer when supplied`

This is my config

```
{
    "label": "zzzz",
    "root": "/home/xxx",
    "host": "xxxx",
    "port": 22,
    "username": "xxxx",
    "password": false,
    "passphrase": false,
    "privateKeyPath": "/Users/xxx/.ssh/id_rsa"
}

**Comment by stevenshave** [comment]
I have the same error, which first started on 8/2/2019.  Before this date, '"passphrase": false' was accepted.

**Comment by wkerzendorf** [comment]
@stevenshave - thanks for the update.

**Comment by wkerzendorf** [comment]
this problem seems to have gone - but now it just sits idle on orange and never connects. Is there anywhere to see a log to get a feeling of what it is doing?

**Comment by SchoofsKelvin** [comment]
It's because `passphrase` should either be a string (the actual passphrase), or `true`, which means "prompt me for it".

> this problem seems to have gone - but now it just sits idle on orange and never connects. Is there anywhere to see a log to get a feeling of what it is doing?

I recently added some basic logging (#79), but it's not very detailed right now. If you could provide me a config file that more or less resembles your setup, I might be able to reproduce the "idle on orange" issue.
