### ISSUE TITLE
Special characters in the passphrase might break authentication

### ISSUE THREAD

**Issue by DavideBecker** [SchoofsKelvin/vscode-sshfs#105]
I've wondered why I could connect via password, but not via SSH key. Turns out my passphase has some special characters in it that appear to break the authentification. `*`, `$`, `#` and `!`. Not sure which one it is, but it worked with a newly generated key and a very basic passphrase.

Other than that, really awesome extension by the way.

**Comment by SchoofsKelvin** [comment]
How is the passphrase loaded? Are you using `"passphrase": "PASS"` in your config, or using `"passphrase": true` to make vscode prompt you for it?

**Comment by nisargthakkar** [comment]
I'm facing the same issue. My institution requires passwords to contain special characters.
I put password in the config file as:
`"password": "MY_PASSWORD"`
With this, I am still prompted to type in my password every time I try to connect.

**Comment by SchoofsKelvin** [comment]
I'll make a test user on my test server later on and see if I can reproduce this. As far as I know, the password shouldn't be altered, except for the standard JSON parsing that happens when reading config files. If your password contains `\` (or `"`), that might then indeed be the case.

I added a rudimentary Settings UI yesterday, which you can open using the command `SSH FS: Open settings and edit configurations`. If you enter your password there and save, it'll make sure it's written with the right escape characters and such.

**Comment by nisargthakkar** [comment]
I just tried the settings ui, but it didn't help. I recently changed my password and before this, special characters used to work. For my personal machine, passwords with special characters works well.

I tried to debug the issue and it seems like ssh2-streams is unable to connect to the server and the keyboard-interactive event is getting fired.

Also, my institution recently might have modified something in their systems which prevents direct authentication (If that is even possible)
