### ISSUE TITLE
ssh login successfull on second password input

### ISSUE THREAD

**Issue by akela68** [SchoofsKelvin/vscode-sshfs#110]
Hi,

i use the last version of SSH FS on VSC 1.31.1 under linux.
When i connect to a remote host the password-dialog comes up twice.
example config
{
    "label": "UX-222.mydomain.dom",
    "root": "/",
    "host": "192.168.0.222",
    "port": 22,
    "username": "root",
    "password": true
}
How can i release a single password request?

**Comment by SchoofsKelvin** [comment]
This is a known bug, and will actually be resolved in an upcoming feature (#81). It's basically related to how I load configs (multiple times), instead of properly caching them.

As a quick/temporary fix, you can use private keys and an agent. Only requires you to enter a password once every time you restart your system (to load the key in the agent)

**Comment by ouija** [comment]
I was also having similar issues with FileZilla and being prompted constantly for the two-factor auth, so I opted to disable it entirely and follow your adivce on another thread by simply using a private key instead :)
