### ISSUE TITLE
Connect to host using private key stored in proxy

### ISSUE THREAD

**Issue by Astlaan** [SchoofsKelvin/vscode-sshfs#115]
I have a private key in my computer which allows me to connect to the proxy.
In the proxy, I have a private key which allows me to connect to the host (final destination).

However, I haven't figured out how to properly configure this...
Setting the password to true makes it still ask for the passwork, setting to false makes it say "all authentication methods failed", and I have no idea how to make the program fetch the private key from the .ssh folder **in the proxy**.

Is this possible, or do I have to transfer that key to my computer running VScode?

Cheers, nice app :)

**Comment by SchoofsKelvin** [comment]
There indeed isn't a way to make use of a private key on the proxy.

I assume you're using `"hop"` to hop through another connection? But yes, keys have to be local.

Perhaps I could add a feature that uses hopping, but instead of using the hop for a raw socket to the target, actually have the hop initiate the SSH connection using the `ssh` command or so. Wouldn't be easy to implement, and I'm not sure either whether this would be used much anyway. Closing for now.
