### ISSUE TITLE
How to connect to two servers at once?

### ISSUE THREAD

**Issue by someonebob** [SchoofsKelvin/vscode-sshfs#126]
![image](https://user-images.githubusercontent.com/17787636/55600156-d7a90f00-5728-11e9-89f1-ed1b57289eaf.png)
I have two configs setup but I can only connect to one of them. 
When I first added the second server, both worked fine, but after restarting VS Code, only one of them now connects. The other doesn't even when I disconnect the one that does.
Has anyone else ran into this issue?

**Comment by Lnk2past** [comment]
Are you getting any error or anything at all? I am able to open multiple connections simultaneously without any issue. How are you opening the connections?

I have SSH FS v1.14.6 installed with VS Code v1.32.3

**Comment by JustinAddams** [comment]
Can confirm, working fine on Windows 10 with latest VSCode.
Also multiple VSCode windows each with a different connected server also works.

![image](https://user-images.githubusercontent.com/14937219/55843938-6bd20680-5b6d-11e9-95cf-e9f88910b501.png)

**Comment by SchoofsKelvin** [comment]
Can you reproduce this bug, and post the output from `Output > ssh-fs`? *(Passwords should automatically be censored from it, but it's best to check for that, and replace your host with a fake IP/hostname, should you want to keep it private)*

**Comment by SchoofsKelvin** [comment]
I did fix a bug (2386ee1f, live in version 1.16.1 of the extension) where if you have two folders of the same server open, and you remove one them (by rightclicking in the Explorer tab), both would get removed instead of just the one you rightclicked. If you use the Disconnect command (or right click in the tree view), it'll still disconnect all folders.
