### ISSUE TITLE
Error while connecting to SSH FS

### ISSUE THREAD

**Issue by atyshka** [SchoofsKelvin/vscode-sshfs#136]
This is my first ime running ssh-fs 1.16.2 in VS Code and I am unable to connect to my remote computer. I am receiving the following error: `Error while connecting to SSH FS xavier-trt: spawn REG ENOENT`
Any ideas what's causing this?

From some googling I found that it's usually related to a "not found" error but I'm not sure what's missing.

**Comment by atyshka** [comment]
@SchoofsKelvin I can confirm that regular terminal sshfs works just fine

**Comment by SchoofsKelvin** [comment]
Either this is a VSCode bug (Microsoft/vscode#5003) or something caused by the extension trying to access the Windows Registry for PuTTY sessions. I assume you're not on Windows, though?

Post your `Output > ssh-fs`. You can censor hostnames, usernames, etc. Passwords/passphrases should be automatically censored, but it doesn't hurt checking.

**Comment by atyshka** [comment]
My apologies, dumb mistake on my part. I'm on linux, so I set the putty session to auto and that triggered the error. Leaving it blank solved my issue.

**Comment by divStar** [comment]
I know this ticket is long closed, but I just wanted to confirm, that if one is using this extension in VS Code (or VS Codium in my case) on MacOS (12.3 I believe) and trying to connect to a Linux server (I don't know if that matters), leaving PuTTY option blank (instead of Auto-Detect) solves the connection issue, too, because - well, who'd have known - I am not using PuTTY 😄 .

**Comment by marschr** [comment]
Just to report a similar issue, using this with Cursor. Just to report in, I had to set `"putty": false` on the JSON config and after that issued a `CTRL` + `SHIFT` + `P` and **Developer: Reload Window** (or probably restart Cursor) and it worked.
