### ISSUE TITLE
SSH-FS Settings screen empty

### ISSUE THREAD

**Issue by tdjong** [SchoofsKelvin/vscode-sshfs#147]
In our work environment we have very limited internet access. So I installed the extension on my internet connected PC and zipped, transported and unzipped the extension on the restricted workstation.
However I would like to use this extension to edit files on a remote Redhat 6/7 host.
Problem is configuration of the connection.
The screen with the List of Configurations was shown once. The Settings screen has  been empty ever since. I don't have a clue where to start debugging.

**Comment by nralberspolitie** [comment]
On a new installation of VS code 
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
After installing SSH-FS, I also get a blank screen when choosing "Create a SSH FS configuration"
I have openssh installed on windows, and also have a cygwin installation with ssh.

**Comment by nralberspolitie** [comment]
![image](https://user-images.githubusercontent.com/50947683/58241909-1c771c80-7d4e-11e9-85b4-f1e3c29821a6.png)

**Comment by pkostov** [comment]
I have the same problem with 
Version: 1.35.1
Commit: c7d83e57cd18f18026a8162d042843bda1bcf21f
Date: 2019-06-12T14:30:02.622Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

Any news?

**Comment by SchoofsKelvin** [comment]
Are there any errors reported in any of the output windows and/or Developer Tools *(Help > Toggle Developer Tools)* about this? The webview doesn't actually make use of the internet. It only makes use of `vscode-resource:` URLs, which access local files in the extension's installation directory.

**Comment by davo-cc** [comment]
I've seen this same problem and have been unable to overcome it - I even went so far as to completely remove/scrub (with Revo) the entire vsCode installation and re-install the lot but the same result persists.   Fresh installation of SSHFS (v 1.17.0) and vsCode build:

```
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

I'm not familiar enough with vsCode yet to deep dive on the issue, I'm working around it by using another solution to mount as a local drive with an SSHFS interface for windows.  

Debugging output is as follows:

`Unable to write into the file. Please open the file to correct errors/warnings in the file and try again.: Error: Unable to write into the file. Please open the file to correct errors/warnings in the file and try again.
    at e.reject (file:///C:/Users/Davo-CC/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4961:532)
    at e.resolveAndValidate (file:///C:/Users/Davo-CC/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4961:407)
    at async e.doWriteConfiguration (file:///C:/Users/Davo-CC/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:4960:43)
abstractExtensionService.ts:400 [ms-vscode.powershell]: Command `workbench.action.debug.start` appears multiple times in the `commands` section.
6webviewElement.ts:287 [Embedded Page] Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'nonce-41323b19-6d7f-4149-bb76-2cffc7d981fd'". Either the 'unsafe-inline' keyword, a hash ('sha256-pu49Wj68+0mYFq0fp2i91xxFFN3AA2Ia7alobLasOdQ='), or a nonce ('nonce-...') is required to enable inline execution.

abstractTextMateService.ts:471 Line (var e=["require...): longer than 20000 characters, tokenization skipped.`
