### ISSUE TITLE
Modify chmod - or create new file with different chmod

### ISSUE THREAD

**Issue by Duncank** [SchoofsKelvin/vscode-sshfs#167]
When I create a new file or folder via this extension, it is writeable by group, so our php-implementation shows errors on it.
In those cases, I have to open Filezilla in order to change the chmod-permissions.

It would be nice if:
*  The extension could create files with a different chmod (maybe a setting, or a different default at least(
*  the right click menu on a file would show some option to change the chmod.

Is anything like this possible?

**Comment by SchoofsKelvin** [comment]
There actually is an option for this, but it isn't very obvious: https://github.com/SchoofsKelvin/vscode-sshfs/issues/39#issuecomment-431434088
You have to directly change the sshfs config in your `settings.json` instead of using the UI. This will determine the permissions set when saving/creating a new file. It won't change permissions of existing files.

Adding a context menu option to change permissions is possible. I'll look into adding it when I have time, along with adding the above `newFileMode` option to the Settings UI.
