### ISSUE TITLE
SSHFS no longer reads the json used for configurations

### ISSUE THREAD

**Issue by WSLUser** [SchoofsKelvin/vscode-sshfs#172]
VSCode version: 1.39.0(Insiders)
Electron version: 6.0.7 (was switched from the 4.x branch a week ago)

To reproduce:
Open VSCode Insiders, update to latest Insiders, look for a remote workspace to connect to as normal, discover those workspaces no longer exist and right clicking to create a new ssh file system workspace doesn't work either.

**Comment by WSLUser** [comment]
@SchoofsKelvin did you ever look into this

**Comment by SchoofsKelvin** [comment]
I just did a quick check, and configurations created in `.json` files listed _(with absolute paths)_ in `sshfs.configpaths` show up for me. Editing them also saves them to the right file.

Which JSON files are you trying to use?

**Comment by WSLUser** [comment]
I'm using the defaults. I confirmed this is still an issue. If I use the prompt to create the config, it works. But if I simply try right-clicking under SSHFS, I do not get the option to create a new config. So the Explorer View is partially broken.

**Comment by SchoofsKelvin** [comment]
They changed how the `when` clause gets evaluated for `view/item/context` contributions. Basically, I can't make it that rightclicking the view panel while not rightclicking an item shows the new/settings option. Instead, it's now available under the view's menu:
![image](https://user-images.githubusercontent.com/14597409/86825877-34177e80-c090-11ea-8bdf-fb32837ec943.png)

Fixed in 33eb94b, will be available in the next available version, after 1.17.0.
