### ISSUE TITLE
Remote Files Code Content Wipeout When Clicking Save on a Slow Internet

### ISSUE THREAD

**Issue by dixiekun** [SchoofsKelvin/vscode-sshfs#174]
Hello, I've been using this and it works great, one HUGE issue I encounter just recently was that when I'm modifying remote files and then when I click save while my internet connection is slow, it WIPES OUT the entire codes/content of the file in the remote server while my local versions codes are still there.

**Comment by SchoofsKelvin** [comment]
Possibly related to #166.
This might mean that it isn't the file size that matters, but a certain timeout that's being hit. That doesn't explain why the file gets wiped instead of partially written to, though.

While I'll look into this when I have time, I do suggest switching over to [VSCode's Remote SSH](https://code.visualstudio.com/docs/remote/ssh).
