### ISSUE TITLE
some remote folder not shown

### ISSUE THREAD

**Issue by yangshao** [SchoofsKelvin/vscode-sshfs#179]
Hi, After connecting to the remote server, some folders are not shown. what are the possible reasons for this? Thanks.

**Comment by WSLUser** [comment]
the directory you choose to enter is the view you'll have in your workspace. If the folders are outside of that directory, you'll need to go a level back. I usually set mine to my user home and then navigate to the various workspace folders from there.

**Comment by SchoofsKelvin** [comment]
Did you specify anything in the `Root` field in the config? By default this should be `/`, meaning that when you connect, you should `etc`, `bin`, ... as the first directories. Otherwise it might be a permission issue, but in that case the directory should still be visible, but just can't be explored.
