### ISSUE TITLE
Error While Connecting to SSH FS conn_name: spawn REG ENOENT

### ISSUE THREAD

**Issue by rajivkumar02** [SchoofsKelvin/vscode-sshfs#193]
<img width="726" alt="Screenshot 2020-04-05 at 11 44 49 AM" src="https://user-images.githubusercontent.com/32587260/78468211-3259ba00-7733-11ea-99f7-fe27dfeb74a5.png">

**Comment by erkanarslan** [comment]
Did you check this? Last comment solved my problem: https://github.com/SchoofsKelvin/vscode-sshfs/issues/136

**Comment by SchoofsKelvin** [comment]
Similar to what @erkanarslan said, I think your problem is having `"putty": true` in your configuration. The `spawn REG ENOENT` error should be from the extension trying to read the PuTTY configurations from the Windows registry using an .exe program, which probably produces that kind of error on non-Windows systems.

Since your configuration seems to have all the required data (host, credentials, ...) there isn't really a need for PuTTY either. The `"agent": "ssh"` also seems wrong.
