### ISSUE TITLE
ProxyJump stopped working

### ISSUE THREAD

**Issue by 2sn** [SchoofsKelvin/vscode-sshfs#205]
I noticed that since within the last few weeks the 'ProxyJump" option in `.ssh/config` stopped working.  It used to work seamlessly before.

Example `.ssh/config file`

```
Host A
Hostname myproxy.org
User myself

Host B
Hostname myremote.org
User myself
ProxyJump A
```
if I now use `sshfs B:remote local`

it no longer works; I tried for a case where no proxy was needed, and adding the proxy prevented connection.  I can log in using the same configuration.  It got stuck after the line (in 'LogLevel DEBUG3')
```
debug1: Local version string SSH-2.0-OpenSSH_8.3
```

Other info:
```
Fedora 32, Kernel 5.7.7, on all machines involved.
SSHFS version 3.7.0
FUSE library version 3.9.1
using FUSE kernel interface version 7.31
fusermount3 version: 3.9.1
```

**Comment by SchoofsKelvin** [comment]
I think you're reporting this on the wrong repository. This repository is for the [SSH FS extension](https://marketplace.visualstudio.com/items?itemName=Kelvin.vscode-sshfs) for Visual Studio Code. Your issue seems to be about the [Linux command/package](http://www.linuxfromscratch.org/blfs/view/svn/postlfs/sshfs.html) instead.

**Comment by 2sn** [comment]
Thanks.  Sorry about that.
