### ISSUE TITLE
ssh-shell task ignores root path

### ISSUE THREAD

**Issue by axelhuizinga** [SchoofsKelvin/vscode-sshfs#210]
Hi - running a task via the ssh-shell ignores the root path set in the ssh fs config of the open workspace folder.
how do I have to set the root path for execution of tasks on the remote ssh folder?

____
_Rest of this description regarding a 2nd issue moved to #212 by @SchoofsKelvin_

**Comment by SchoofsKelvin** [comment]
Seems like I forgot to do [this](https://github.com/SchoofsKelvin/vscode-sshfs/blob/v1.18.2/src/pseudoTerminal.ts#L32) in [createTaskTerminal](https://github.com/SchoofsKelvin/vscode-sshfs/blob/v1.18.2/src/pseudoTerminal.ts#L72). I'll most likely end up refactoring the latter into using the former.

I'm moving the 2nd part of your issue to a new issue, since it's something separate.
