### ISSUE TITLE
V19 UI issue: the disconnect/connect icon is stuck in disconnect (even on disconnected locations)

### ISSUE THREAD

**Issue by laurencefass** [SchoofsKelvin/vscode-sshfs#231]
Version 19.1+ introduces a new LHS column icon for SSFHFS containing locations that was previously available in v18.3 as an accordion dropdown in the main explorer. 

Connect/diconnect is broken: it only gives an option to disconnect  on locations that not connected. I can open a terminal to the location using v19 UI its the connect/disconnect icon thats broken.

Ive reverted back to v18 which still works fine.

**Comment by SchoofsKelvin** [comment]
I assume you're talking about those icons?
![image](https://user-images.githubusercontent.com/14597409/102895285-b8a26180-4464-11eb-8e4d-f079c71f7f65.png)
Hovering your mouse over them explains what they are, which are, from left to right:
- Add as Workspace folder _(the old connect mechanism, which is probably what you want)_
- Open remote SSH terminal
- Edit configuration
- Disconnect (removes all workspace folders and terminals of this configuration)

The disconnect icon is only meant to disconnect. The disconnect icon is just always displayed (even if it's not connected) for both aesthetic and technical reasons. This is partially because there are 2 ways to connect (workspace folder and/or terminals), so a plain "Connect" button wouldn't make much sense. The extension API doesn't really allow "dynamic icons/buttons" either.

**Comment by laurencefass** [comment]
looks fine after a restart. thanks.
