### ISSUE TITLE
Request for environment customization

### ISSUE THREAD

**Issue by cheese** [SchoofsKelvin/vscode-sshfs#241]
Customization of ssh shell environment is really needed. I don't find a configuration in host config.

For now I can work around this by setting `terminalCommand` to `TERM=xterm-256color $SHELL`. Default value of `TERM` is `vt100` and `PageUp` will not work.

**Comment by bitsandbytes** [comment]
This would be nice - I set the TERM to "xterm", otherwise when I run tmux I don't get the nice colors that it should have.

But I tried the following:
- Set the optional PuTTY value to the name of my putty session,
- In the putty session, under Connection->Data->Terminal Details->Terminal-type string is "xterm".

I was thinking that when sshfs gets session details from putty it should include the "Terminal-type string" as well. Is that not the case?

**Comment by SchoofsKelvin** [comment]
> I was thinking that when sshfs gets session details from putty it should include the "Terminal-type string" as well. Is that not the case?

PuTTY sessions aren't supported "natively" by the extension. It actually goes through the Windows registry and read certain config values from there. Currently only these fields are actually used:
https://github.com/SchoofsKelvin/vscode-sshfs/blob/94f2c37ab0082da4370a0c10a176a66f9bb4bfc1/src/putty.ts#L12-L28
_and `proxymethod` only supports `HTTP`, `SOCKS v4` and `SOCKS v5` right now_

Copying over environment variables (including indirect ones such as that `TERM`) isn't a bad idea. I'll add that as a part of this issue, since the whole environment customization is 90% of the work.

__________
_Currently busy with my thesis, so probably won't be able to do anything until at least mid-June_

**Comment by bitsandbytes** [comment]
The details that are copied over make sense. I was reading too much into it when I saw that PuTTY sessions were read into sshfs.

But I'm glad you like the idea of copying over env vars. That bit would be useful in lots of different ways.
