### ISSUE TITLE
Opening remote .js file | Initiliazing JS/TS language feature

### ISSUE THREAD

**Issue by ElmanRojas** [SchoofsKelvin/vscode-sshfs#248]
I am working on remote files only sitting on a Linux server but when i open a file the message Initiliazing JS/TS language feature keeps showing and never goes ways.
![image](https://user-images.githubusercontent.com/82179830/114088636-38710200-9883-11eb-9fbd-896a3556c555.png)

**Comment by SchoofsKelvin** [comment]
Was able to reproduce.

This seems more like an issue in the `TypeScript and JavaScript Language Features` built-in extension. You (or I) should report it, since it's probably that extension not being able to handle remote file systems.

Possibly related issues on their tracker: microsoft/vscode#119268 microsoft/vscode#118643 microsoft/vscode#109847
I'll see later if I can figure out why it happens, e.g. it trying to look for a `jsconfig.json` or something similar.
