### ISSUE TITLE
availability of variables e.g. workingDirectory in Terminal Command

### ISSUE THREAD

**Issue by creative-resort** [SchoofsKelvin/vscode-sshfs#249]
Which variables are we able to use in the configuration?

I want to configure the Terminal Command to something like:
`export STRTDIR="${workingDirectory}";/bin/bash -i`

How should I go about this?

**Comment by SchoofsKelvin** [comment]
Added that (task) variables in `Terminal Command` also get replaced now (7a779f8)

Mind that it only supports "remote" task variables, as mentioned in #232. You'll have to use e.g. `${remoteWorkspaceFolder}`, although I could add support for "local" task variables (e.g. `${relativeFile}` instead of `${remoteRelativeFile}`) later on.

It'll probably take a day or two before I push an update with this new feature. If you need this immediately, you can download a built version with the change [here](https://github.com/SchoofsKelvin/vscode-sshfs/actions/runs/741582317) already.

**Comment by SchoofsKelvin** [comment]
It's also now available in version v1.20.1 of the extension, released a few minutes ago.
