### ISSUE TITLE
Configure to open/write with sudo?

### ISSUE THREAD

**Issue by theoDiefenthal** [SchoofsKelvin/vscode-sshfs#28]
Hi there,

I have access to a remote system with a given user (not root). 

This user has sudo priviliges, thus I can view/edit any file in an SSH session and I would like to use VS Code SSH FS plugin to edit some configuration files. But sadly, it doesn't allow me to write those config files due to missing permissions. 

Would it be possible to include a "sudo" option in configuration which will kind of run any read/write operation with sudo?

**Comment by SchoofsKelvin** [comment]
I'll be looking into this, but it's not planned right now.
Apparently it *can* be done, although I'll have to look into something mentioned here: mscdex/ssh2#287

**Comment by ssanthos** [comment]
Would love to have support for this out of the box.

I'm currently working around this by always making a copy of the file I want to edit to a folder where I have write permissions, edit the file in VS Code, and then use a ssh terminal to copy the edited file back using sudo.

**Comment by SchoofsKelvin** [comment]
This feature is now added (288f4ad) and published (extension version 1.10.0)

I'll add documentation (#43) for it soon, but here's a summary:
- There's a new field `sftpCommand` added for sshfs configurations
- If the field is absent, the extension will use the `sftp` subsystem, as it always did
- If it's present, it'll run the given command instead of starting the given subsystem
- For most distributions (e.g. Ubuntu), the default is `/usr/lib/openssh/sftp-server` (sftp subsystem)
- You can change it to something else, e.g. `sudo /usr/lib/openssh/sftp-server`

An example configuration could be;
```json
{
  "root": "/",
  "putty": "test",
  "name": "test",
  "sftpCommand": "sudo /usr/lib/openssh/sftp-server"
}
```

With this configuration, you'd be accessing files as root, or any other user, should you add the right parameter to the sudo command. Mind that creating files will also be in name of the given user, thus the ownership of the new file might be incorrect.

If there are any issues, feel free to post them here or make a new issue.

**Comment by prog1407** [comment]
Thanks a lot for the nice extension. I also really need to have this sudo feature but unfortunately didn't manage to make it work for me. When I press connect it asks for password once and then status of configuration becomes orange. I can imagine that it tries to connect and ideally should ask me for sudo password once again but it doesn't

my config

`"sshfs.configs": [
        {
            "root": "/home/red",
            "host": "192.168.100.100",
            "port": 22,
            "username": "red",
            "password": true,
            "name": "homeserv",
            "sftpCommand": "sudo /usr/lib/openssh/sftp-server"
        }
    ]`
I'm running debian 9

**Comment by EwanSadie** [comment]
I am running this from Windows 10. I need to "sudo su - nextusername" but this does not work.
I basically want to do the same as I do in WinSCP using scp and I change the shell

**Comment by SchoofsKelvin** [comment]
I'm currently adding better support for sudo and sftpCommand. You can follow issue #104 for progress.
