### ISSUE TITLE
Outline not working (for 4GL Informix)

### ISSUE THREAD

**Issue by d2k2-git** [SchoofsKelvin/vscode-sshfs#297]
Outline for functions/procedures is not working when opening *.4gl files with ssh fs while the outline works when opening files on local maschine.

![image](https://user-images.githubusercontent.com/6248041/137334364-48de5aed-2166-43fd-a9e5-1f51f69bef05.png)

Seems to be only problem with the 4GL plugin.
https://marketplace.visualstudio.com/items?itemName=CristianRengifo.informix4gl

with another ssh addon the outline seem to work.

**Comment by SchoofsKelvin** [comment]
Which "another ssh addon" are you talking about? This extension uses the extension API to make VS Code talk "directly" with the remote server over SSH. Another kind of addon basically synchronizes a remote folder on the local file system (akin to native `sshfs` mounting) and just makes VS Code use those local files.

After taking a look at that extension, it seems like they [explicitly require on-disk files](https://github.com/INGCRENGIFO/VsCodeInformix4GL/blob/9a361b7103e65a7a4e06a1b08556dc0afc130431/src/extension.ts#L7), which is why it stops working for this extension, as the remote files are accessed through `ssh://` instead of `file://` (or e.g. `C:/path/` or `/home/user` which internally uses `file://`).
