### ISSUE TITLE
GIT repository not detected in VSCode Source Control

### ISSUE THREAD

**Issue by paulklemm** [SchoofsKelvin/vscode-sshfs#31]
I've successfully mounted a remote folder with the plugin. It contains a GIT controlled project. VSCode however does not detect it as such. Is this intended behavior?

![image](https://user-images.githubusercontent.com/2169489/43518191-8e0daf40-958b-11e8-99e8-53e8e9d414f5.png)

![image](https://user-images.githubusercontent.com/2169489/43518200-94764ba8-958b-11e8-971c-eae88dede31b.png)

**Comment by SchoofsKelvin** [comment]
It doesn't seem like I can (easily) add support for this right now. My hope is that once I implement some other features, most noticeably the SearchProvider, vscode will recognize the git repositories again.

Since the Git Output shows it is running `git rev-parse --show-toplevel`, I'm not sure whether that'll actually work.

**Comment by brentashley** [comment]
The issue seems to be that the SSHFS workspace root looks like "/" to vscode (hover over the folders in workspace to see their path) so when vscode passes the directory / to the external git command, git looks in "C:/" for repositories.  Possibly if the SSHFS filesystem was mounted to a driveletter (say, R:), the external git command could find the .git files in R:/

**Comment by brentashley** [comment]
Apart from the git issue, this could potentially affect any vscode feature or extension that uses the file path.  for instance if I were to use a plugin that modifies a file and apply it to a file in my workspace called /etc/hosts I could end up overwriting my workstation's /etc/hosts file.

**Comment by SchoofsKelvin** [comment]
I just handled another issue (#42) related to extensions not supporting remote files. The problem is that with git, the git.exe can't access `ssh://` URLs, as those are provided by the extension _within vscode_.

There are some extensions created before the FileSystemProvider API got added that actually write the files to the local disk, and just upload them when they're modified. For now, it's just waiting for existing extensions to make use of the new API, instead of directly reading/writing from/to disk.

**Comment by brentashley** [comment]
Thanks for the info.  I guess we will likely have to wait until support for ssh:// URLs gets into the builtin git integration.  I can't see third parties being too motivated to write git support extensions when it's built in.

**Comment by paulklemm** [comment]
Are there any open issues on this that we can support to speed up the process?

**Comment by SchoofsKelvin** [comment]
There doesn't seem to be an issue about this on the vscode GitHub, although it might've been mentioned in related issues.

**Comment by paulklemm** [comment]
Ok I guess we'll put this on ice for now since there is not much we can do about it.

**Comment by floatingpurr** [comment]
Same problem here. I was wondering if the problem remarked by @brentashley can have any serious drawback also on macOS.

**Comment by WSLUser** [comment]
See the linked issues.

**Comment by osterik** [comment]
Workaround: use new feature called "Visual Studio Code Remote Development Extension Pack"
> We just announced remote development with VS Code, check out the blog post for details https://code.visualstudio.com/blogs/2019/05/02/remote-development

[via](https://github.com/microsoft/vscode/issues/66046#issuecomment-488791480)

**Comment by sergei3000** [comment]
@osterik this is not a workaround for many people because it requires to open connection to some Microsoft's websites from the remote server, which is not possible on many corporate servers.

**Comment by csaska** [comment]
If you folks still want this support, I suggest you go like the new issue I opened. 

https://github.com/microsoft/vscode/issues/109954

**Comment by mitchelangelo** [comment]
SSH FS is a useful plugin, a work around involving caching the target directory locally and restoring source control features would be ideal. That way you don't have to overcome the permission issue, you could add a hook to save which saves both locally to the cached repo and remotely to the source for synchronization. You might also have to push from local directory and then trigger a pull request on the remote to keep them on the same commit. That could be a possible work around for SSH FS.
