### ISSUE TITLE
No Config Discovered

### ISSUE THREAD

**Issue by carolinesatriano** [SchoofsKelvin/vscode-sshfs#319]
I have the same config as my teammates but I am not able to connect because of a configuration issue. The server is allowing me in. Is there a remediation for this?
<img width="1217" alt="Screen Shot 2022-01-03 at 10 39 37 AM" src="https://user-images.githubusercontent.com/68923493/147956044-68840fad-b173-41fc-9715-b615e07bfaeb.png">

**Comment by SchoofsKelvin** [comment]
Your config's name is `wimi`, yet you're trying to use a config named `ipcsmlaas`, that's why it complains.

I don't know how you created a connection and ended up with it trying to connect to `ipcsmlaas`. I assume you're using some Git-committed workspace file that uses `ssh://ipcsmlaas/...` as workspace folder, or something similar. If your team is sharing configs like that, mind that your SSH FS configs should also match, _or at least the Name field_.

**Comment by carolinesatriano** [comment]
Thanks for the quick response. Now getting this directory error. Does that have to do with the private key or root?

**Comment by SchoofsKelvin** [comment]
This issue would be easier to solve with debug logs, so please follow these steps:
- Add `DEBUG_SSH2` to the `sshfs.flags` array in VS Code's User Settings (settings.json)
    e.g. `"sshfs.flags": ["DEBUG_SSH2"]`
    - See [this issue](https://github.com/SchoofsKelvin/vscode-sshfs/issues/270) for more information about adding flags
- If you already have a connection open, close it completely (or even reload the window)
- Go to `Output > SSH FS` and copy the log from there after replicating your bug
-  While it should censor passwords/passphrases, I recommend checking it for (other) sensitive data first.
    _(especially since `DEBUG_SSH2` activates some internal logging, which is less likely to be censored)_
