### ISSUE TITLE
Why task ends while using slurm commands?

### ISSUE THREAD

**Issue by hamad12a** [SchoofsKelvin/vscode-sshfs#330]
My task is like the following,

	"tasks": {
		"version": "2.0.0",
		"tasks": [
			{
				"label": "test task",
				"type": "ssh-shell",
				"host": "hostname",
				"command": "srun -p short ~/workplace/go ~/workplace/NN/Sn130.txt",
				"problemMatcher": []
			}
		]
	}
	
Executing the task doesn't wait to receive the output from the host; in contrast for a real-time shell session, the execution of such command lasts for some time to echo the result.

**Comment by SchoofsKelvin** [comment]
Do you see any output at all? Since v1.24.0 of the extension terminals that exit within 5 seconds should remain open, in case the command failed to execute. Also, is `srun` globally available, or something added (to your `PATH`) in a profile script? Depending on your OS and default shell, some profile scripts might not run, making it that your command (or environment variables used by your command) aren't available.

**Comment by hamad12a** [comment]
No, the command srun is NOT an alias or a function; it is a Slurm command that is available globally. 
The terminal remains open but the expected output is absent. Running the task opens a terminal without output, i.e.,

`> Executing task: test task <

Connecting to xxxx@host...


Terminal will be reused by tasks, press any key to close it.
`

**Comment by SchoofsKelvin** [comment]
> Additionally, when I login directly in real-time with the terminal I don't find the expected output either.

I assume you mean a "regular" remote SSH terminal created by the extension instead of a task-specific one?

That `Terminal session closed` log statement, is it logged basically immediately after the `Starting shell` line? That last line indicates that the remote SSH server reported that the process exited successfully. Only other issue I can think of is a misconfigured (non-loaded) environment, I don't know if `srun` expects certain [environment variables](https://slurm.schedmd.com/srun.html#SECTION_INPUT-ENVIRONMENT-VARIABLES) to be set.

Perhaps setting the [debug level](https://slurm.schedmd.com/srun.html#OPT_slurmd-debug) to the highest might help? A quick glance at the documentation shows that it only logs errors by default, but perhaps it's silently successfully exiting for an unexpected reason it doesn't count as one. Since `sinfo` yields output, I doubt it's an issue with the extension silently discarding the output.

**Comment by hamad12a** [comment]
the remote terminal created by the extension is similar to the one that appears in the captured snippet of the extension [https://github.com/SchoofsKelvin/vscode-sshfs/raw/master/media/shell-tasks.png](url) 
The `Terminal session closed` log statement isn't logged immediately; takes more than one second to appear.

**Comment by hamad12a** [comment]
I am writing another reply but might be deleted if what I'm saying doesn't make sense.
Why module is reported as,
`bash: module: command not found`
I want to load modules of Slurm to be able to run `srun`.

**Comment by SchoofsKelvin** [comment]
Looks like it's indeed an environment/profile issue. [This SO question](https://stackoverflow.com/q/59182655/14274597) mentions  a `LD_LIBRARY_PATH` in the comments, similar to the answers on [this question](https://stackoverflow.com/questions/18410679/loading-shared-libraries-with-ssh-framework) that was specifically for SSH.

I'll be closing this ticket for now. If it's an issue with the extension (perhaps an issue with it not being a login shell or similar), feel free to comment and reopen it.

**Comment by hamad12a** [comment]
Indeed the problem was the absence of the `LD_LIBRARY_PATH` path. After making use of the one-line command `export LD_LIBRARY_PATH=/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4/lib:/opt/ohpc/pub/compiler/gcc/8.3.0/lib64
` in `.bash_profile` file and not `.bashrc` file it worked normally.
