### ISSUE TITLE
Is there a way to open a file from the Terminal in the editor without VSC file explorer?

### ISSUE THREAD

**Issue by hamad12a** [SchoofsKelvin/vscode-sshfs#342]
There is a feature in VSC in the local file system, using Ctrl+click buttons. In the Terminal area, which will open any file even within a specific path, in the editor. It will be instrumental if this extension provides that feature.

**Comment by SchoofsKelvin** [comment]
The extension already supports Terminal Links since v1.19.1, although with limited support. It should correctly identify absolute paths. It can't handle relative paths right now, as I'd have to figure out a way for all popular terminals to seamlessly report their working directory whenever it changes. _That, or keep track of whenever the user sends `cd ...` commands and hope nothing weird happens, like using an alias for `cd`._

Mind that out-of-the-box, VS Code should also allow you to Ctrl+click any word including dots, e.g. `file.ext` and it'll give you a quick picker file search popup. Although it won't scan the remote SSH filesystem, it will suggest open files with the given name.
