### ISSUE TITLE
Error handling uri in version 1.71.0

### ISSUE THREAD

**Issue by KenHarding** [SchoofsKelvin/vscode-sshfs#354]
VS code is failing to open because of the number of Error handling uri messages.  This just began after the update to version 1.71.0.
Connecting to an IBM i os version 7.3.
![VS code error snip](https://user-images.githubusercontent.com/113120472/189154234-61386f60-e5ff-4e0e-b700-744d623cbd10.PNG)
Any way to fix this?

**Comment by ElmarHarbecke** [comment]
Hello, same problem here. 
I have tried some exludes in the config, but that doesn't work.

**Comment by simonbooth1968** [comment]
Hello I am having the same issue too and it more or less locks out VS Code and causes other issues. Very very frustrating. Looks like there could be an issue with the SSH FS configuration because it looks like this error could be because it isn't loading up the configuration up in the SSH FS extension.  When this happens you get caught in a never ending loop of 'Error handing uri' for every file in the workspace and takes forever. 

The only way to clear is to keep uninstalling and reinstalling the extension, which is a pain.

**Comment by viatoswelz** [comment]
Same here

**Comment by TheFacelessOne** [comment]
Same problem
<img width="414" alt="image" src="https://user-images.githubusercontent.com/27927292/209165646-a71b6f81-1ca4-40ca-8693-853d638e1a8e.png">

**Comment by SupermaNO** [comment]
UP. Same here

**Comment by SchoofsKelvin** [comment]
Could not reproduce, although I'm already on VS Code 1.76.2 due to being very late with maintaining the extension. If the issue does still happen, please reopen with (debug-enabled) logs.
