### ISSUE TITLE
How to automatically connect SSH when VSCode startup?

### ISSUE THREAD

**Issue by ioslide** [SchoofsKelvin/vscode-sshfs#356]

**Comment by SchoofsKelvin** [comment]
Not exactly sure what you mean. Does VS Code support automatically opening (local) workspace directories, with or without using an extension? If so, you can make it open `ssh://<config-name>/absolute/path/to/folder` instead of `/some/local/path`.

Perhaps a shortcut opening VS Code with a `ssh://` URI would work, if URIs work (see #335)
