### ISSUE TITLE
Couldn't start a terminal for xxx: All configured authentication methods failed

### ISSUE THREAD

**Issue by elayoutable** [SchoofsKelvin/vscode-sshfs#378]
Hi there,

The extension is very great! Thank you very much! It worked perfect some weeks ago. 

But now I´ve got the message: 
Couldn't start a terminal for xxx: All configured authentication methods failed. 

The ssh key is the same. I´ve tried the login with puuty (same sshkey) and no problems. I didn´t change anything.

Have you got a tipp for me? I´ve tried the older version 1.25 but with the same result.
Thank you!

**Comment by SchoofsKelvin** [comment]
Did you recently update your server or the OpenSSH server running on it? If so, you could check the build I mentioned in #309.

Otherwise provide me with your debug logs, so please follow these steps:
- Add `DEBUG_SSH2` to the `sshfs.flags` array in VS Code's User Settings (settings.json)
    e.g. `"sshfs.flags": ["DEBUG_SSH2"]`
    - See [this issue](https://github.com/SchoofsKelvin/vscode-sshfs/issues/270) for more information about adding flags
- If you already have a connection open, close it completely (or even reload the window)
- Go to `Output > SSH FS` and copy the log from there after replicating your bug
-  While it should censor passwords/passphrases, I recommend checking it for (other) sensitive data first.
    _(especially since `DEBUG_SSH2` activates some internal logging, which is less likely to be censored)_

**Comment by SchoofsKelvin** [comment]
You can use the `Extensions: Install from VSIX...` command to install the `.vsix` file (after unzipping) from the build.

The output is in the Output pane, in the same place as the Terminal pane. You can use the `View: Toggle Output` command and then selecting `SSH FS` in the dropdown.

**Comment by SchoofsKelvin** [comment]
I've published a new version of the extension ([v1.62.1](https://github.com/SchoofsKelvin/vscode-sshfs/releases/tag/v1.26.1)) which includes this fix, so it's not necessary anymore to manually install the custom build to test it. If you still encounter this issue, comment on (and reopen) this issue.
