### ISSUE TITLE
default umask setting in SSHFS?

### ISSUE THREAD

**Issue by pjmcquade** [SchoofsKelvin/vscode-sshfs#39]
Hi Folks, 

Just started using the extension and googled for quite a bit before I posted, but when I create a file on my remote Linux system, it creates the files with 666 octal and I'd like to change that to 644 or 640 (i.e. umask 022 or 027.

Where do I configure this?

Thanks!

**Comment by DarthSpock** [comment]
Default of 644 would be optimal. We can always chmod it if we need to in special circumstance. (Maybe add a setting that can be changed in global or workspace)

**Comment by SchoofsKelvin** [comment]
**35e3ab3 Added and published under version 1.11.1**

There's now a new config option `newFileMode`, which can be a umask number *(e.g. `420`)* or an octal umask string *(e.g. `"644")* which will be used when creating new files.

I might add a general `sshfs.newFileMode` option to the User Settings to fallback on should it not be defined for the config itself. Otherwise, including now when the new option isn't provided, it uses the default as defined by ssh2-streams, which is octal 666.

*Note to self: #43*
