### ISSUE TITLE
Python completion doesn't work

### ISSUE THREAD

**Issue by gigi206** [SchoofsKelvin/vscode-sshfs#45]
Hello,

I tried to open python file and I have only the syntax color that works. Completion, linting, etc.. don't work.

Is there a way for it works ?

**Comment by SchoofsKelvin** [comment]
Duplicate of #42

**Comment by selpoG** [comment]
I think the cause of the problem is vscode cannot find remote python.
If you select python version via vscode, `"python.pythonPath"` will be `"home/local_user/.pyenv/shims/python2"`, which should be `"/home/remote_user/.pyenv/shims/python2"`.
If there is any way to tell vscode the correct path of remote python, linter will work properly.

**Comment by jlam17** [comment]
Is there a way to hack around this?
