### ISSUE TITLE
Issues with configs not "saving" properly I guess? Until reload?

### ISSUE THREAD

**Issue by jfrux** [SchoofsKelvin/vscode-sshfs#62]
The readme said 1.23 was an issue but it was supposedly fixed / closed in 1.24 but I'm running 1.28.x?

Any updates on this or is this something I can remedy on my end?

**Comment by DarthSpock** [comment]
Try Insiders. It appeared to fix the issue for me as well.

**Comment by jfrux** [comment]
Insiders is what? Another plugin?

**Comment by DarthSpock** [comment]
VS Code. You can download the stable or Insiders. Insiders contains updates and fixes that are pushed out every night.Stable is only updated every month. Since I was starting up a new dev environment in my VM, I just removed Code, all extensions, and settings and started fresh.

**Comment by jfrux** [comment]
My bad! I’m such a noob.

Thx man

**Comment by SchoofsKelvin** [comment]
The original bug, that I mentioned in the README, made it that when I changed the configs, vscode wouldn't properly recognize the new settings and act weird. It seems something similar is happening now again, or maybe it's just the same bug.

I'm closing this issue for now, since it seems to (still) be on vscode's end.
