### ISSUE TITLE
Add proxyjump option

### ISSUE THREAD

**Issue by dragz** [SchoofsKelvin/vscode-sshfs#66]
Hi (and thanks for a great extension. This is the final piece of the puzzle that enables me to finally dump emacs)

It would be nice to be able to have a proxyjump option to invoke the ssh -J option when one needs to connect through a jumphost. I found the undocumented hop option through intellisense and it works fine, but having to create a separate config for the jumphost is a bit cumbersome.

Again, thanks for a great extension!

**Comment by SchoofsKelvin** [comment]
I might rework the config parser to allow the ssh config to be embedded in the proxy field. Another thing I'm planning on adding is parsing `user@host:/root` URLs sooner or later.

In what (other) way would you want this proxyjump option to be available?

**Comment by dragz** [comment]
I think just having a way to be specify general config options should be fine. E.g. having a way to specify anything that would be accepted on ssh -o ....... is sufficient.

Also, it would be nice if one could just point to a ssh config file. I prefer to keep all my configs in one place as I tend to forget where I put stuff if it get spread over to many configurations.

**Comment by SchoofsKelvin** [comment]
The thing is that I don't use any binary program or so. I use the [ssh2](https://www.npmjs.com/package/ssh2) library. While it does support some options, it is (just) enough for terminals and SFTP with support for (most) proxies, but not a lot more.

While I could switch to using a binary (and I actually have a local branch where that's a config option), that wouldn't be crossplatform, which it is supposed to be as a vscode extension. Like I mentioned, I have a local branch  I'm testing something like this on, but it is very crude and makes it a bit complex for the user too.

Reading `~/.ssh/config` is something I've been looking into the past week, and will probably be added soon. Again, due to the library I use (and lack of a better crossplatform, non-npm-install-script one to my knowledge), a lot of options in these files would just be ignored. Like with PuTTY sessions on Windows, the extension would only extract the information it knows how to handle.

**Comment by lw394** [comment]
@SchoofsKelvin , this has been a super helpful extension , I've been using it everyday for weeks now to develop on my linux machine from my macbook, it's been pretty stable, thank you.  

Recently, however I've been trying to do the same on new host and I'm having some trouble. It's defined in my ~/.ssh/config as follows:
Host my_host
    HostName my_host.example.com
    HostName %h
    ProxyCommand ssh -W %h:%p secure.example.com

Based on this thread and your existing documentation, I've tried something like this in sshfs.configs, but no luck yet.  Any idea what I'm doing wrong?

"sshfs.configs": [
  
    {
        "root": "/home/username",
        "host": "secure.example.com",
        "username": "username",
        "port": 22,
        "password": false,
        "name": "secure"
    },
    {
        "root": "/home/username",
        "host": "my_host.example.com",
        "username": "username",
        "port": 21,
        "password": true,
        "hop": "secure",
        "name": "my_host"
    }
]

**Comment by SchoofsKelvin** [comment]
When `password` isn't a string or `true`, I just pass it on to the ssh2 library. I'm not sure what your `"password": false` does, but it doesn't seem right. I'd say that the proxy can't authenticate. Is there no error? *(if you can use the `secure` config as workspace folder, then it should also function as hop)*

**Comment by lw394** [comment]
Hi @SchoofsKelvin , thanks for the reply.  

Btw, from the terminal I can `ssh username@secure.example.com`, and also `sshfs username@secure.example.com:/home/username local_mount_folder` without any issues, in fact, without even a password prompt. 
However, I changed the `secure` config to `"password": true`, and cannot connect even then, so that's likely the root cause as you suspected.  I get the following error: `Error while connecting to SSH FS secur.....: All configured authentication methods failed`

Any idea what might be the issue here?

**Comment by SchoofsKelvin** [comment]
I'll run some tests, as it seems to me the hop fails to connect/authenticate, but doesn't provide a proper error.

**Comment by jumpkick** [comment]
Found I was able to use a private key to the jumphost, but not [a different private key] from the jumphost to the final server...   Tried putting final server's private key on my local machine both as a file and as a privateKey string in addition to trying to specify a keyfile on the jumphost.

I did eventually get through to the final server by allowing password auth though, and specifying a password.   So that would appear to be a limitation of the current plug-in, which is understandable given it sits atop a portable npm module.

**Comment by SchoofsKelvin** [comment]
If both private keys are on the local machine, with `privateKeyPath` in the hop's configuration and the "top" configuration pointing to the right file, it should make use of the right key for the right machine.

Currently, the connection with a hop gets made like this:
- Create socket for top configuration
	- Has `hop`, create a direct connection to the hop
	- Use that connection to create a SSH session with the hop
This acts the same as directly connecting to the hop, but without initiating SFTP.
	- Create a to the hop, to a socket from the hop to the actual target machine
- The resulting socket/tunnel/channel is then used to initiate a SSH session
- Create SSH session (with the targeted machine) on the resulting socket
- Create SFTP session from the SSH session

While without hopping, it's just more direct:
- Create a socket with the top configuration
	- No hop/proxy, so it's just a direct socket
- Use resulting socket for SSH and then SFTP

If a hop-less connection to both the hop and the targeted machine work, then using one as a hop for the other should work too.

**Comment by pemontto** [comment]
Just pitching in for support of ssh_config. I traverse through multiple hosts that are all behind a bastion which requires a OTP. I make heavy use of the config file to configure the multiple proxycommands, but most importantly to use ssh muxing so I don't need to re-auth using the OTP for every connection!

**Comment by SchoofsKelvin** [comment]
I'm in the progress of reworking how configs are loaded and such, with already some new features implemented (e.g. settings UI, as mentioned in #81)

Parsing "native" ssh config files is on my TODO-list, but I'm not sure how well proxycommands will work. I do support some custom command stuff right now, but that was already quite tricky to implement.

**Comment by SchoofsKelvin** [comment]
I am planning on adding support for multiple jumps at once using the **ProxyJump** keyword (part of #107)

I've researched multiplexing (using ControlPath) for a while now, but as far I can tell, I can't use it in vscode. The mux protocol requires sending over (native) file descriptors, which doesn't seem possible in Node.js.
