### ISSUE TITLE
support ssh hopping

### ISSUE THREAD

**Issue by xfgong** [SchoofsKelvin/vscode-sshfs#7]
Hi Kelvin, 
 
My dev host is behind a jumper server,  support ssh hopping which ssh2 [already supported](https://github.com/mscdex/ssh2#connection-hopping)  will be nice.

**Comment by SchoofsKelvin** [comment]
I'll see if I can implement this using ssh2's `forwardOut` method, and otherwise use something similar to the netcat example you linked.

The feature will most likely be used like this:
*(using the same example IP/ports from the ssh2 example)*

```js
{
    "sshfs.configs": [
        // The hop to go through
        {
            "name": "conn1",
            "host": "192.168.1.1",
            "username": "user1",
            "password": "password1"
        },
        // The actual wanted SSH connection
        {
            "name": "conn2",
            "host": "192.168.1.2",
            "username": "user2",
            "password": "password2",
            // New field (using existing configuration)
            "hop": "conn1"
        },
        // The actual wanted SSH connection (configured another way)
        {
            "name": "conn2-alternative",
            "host": "192.168.1.2",
            "username": "user2",
            "password": "password2",
            // New field (using inline configuration)
            "hop": {
                "host": "192.168.1.1",
                "username": "user1",
                "password": "password1"
            }
        }
    ]
}
```
The `"hop": "conn1"` would be implemented first. I might add the inline version too (either would work), but might not be present in the first version of this feature.

**Comment by SchoofsKelvin** [comment]
Connection hopping has been added (eb2425a) in version 1.7.0

Currently, you'll have to add the hop as a configuration, then add `"hop": "hop-config"` to your actual configuration you want to connect with.
