### ISSUE TITLE
config for vscode-sshfs

### ISSUE THREAD

**Issue by peter73421** [SchoofsKelvin/vscode-sshfs#75]
I want to use vscode-sshfs to my remote embedded linux device

```
user: root 
eth0  inet addr:192.168.15.124  Bcast:192.168.15.255  Mask:255.255.255.0

```
I have ssh available to this device. How should I configure sshfs?

**Comment by SchoofsKelvin** [comment]
The [README.md](https://github.com/SchoofsKelvin/vscode-sshfs/blob/master/README.md) has some information/examples, but a minimalistic configuration would be:
```json
"sshfs.configs": [
    {
        "name": "embedded",
        "host": "192.168.15.124",
        "username": "root",
        "password": true
    }
]
```
That'll prompt for your password every time the workspace gets loaded. Alternatively, replace `true` with `"PASSWORD"` or (see the README to) make use of private keys or an agent. You can add e.g. `"root": "/root"` to make `/root` instead of `/` the workspace folder. As I mentioned, the README.md has some information, which is worth reading.
