### ISSUE TITLE
Is there any way to use RSA private keys from AWS?

### ISSUE THREAD

**Issue by RioBautista** [SchoofsKelvin/vscode-sshfs#90]
I tried using both privateKeyPath and privateKey with my AWS .pem file but it tells me that it is not a recognised private key format.

Is there any way to get this working on AWS?

**Comment by SchoofsKelvin** [comment]
Parsing keys is done by an [underlying library](https://www.npmjs.com/package/ssh2-streams#utility-methods) that supports several types. It lists OpenSSH, which by default is a 2048-bit RSA key. According to a quick google search, it seems as if Amazon uses the same kind of keys.

I'm basing this on information from [this page](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html). It also mentions importing third-party keys to Amazon, instead of using their generator.

Right now, I'm not entirely sure what format your key is, and what went wrong with parsing it.

**Comment by tegarimansyah** [comment]
Hi @SchoofsKelvin, amazing project!

I just want to confirm that I can use my AWS key (.pem). Lately I also had a problem with connecting to my server, but it just because I put wrong path. I also thought that it may be permission problem (aws force us to give 400 to key file) but it is not an issue.

**Comment by SchoofsKelvin** [comment]
Since it seems like AWS keys work, I'll close this issue.
