### ISSUE TITLE
Option to disable auto-connect on Startup?

### ISSUE THREAD

**Issue by knobhead** [SchoofsKelvin/vscode-sshfs#99]
Hi,
thanks for your comfortable extension!

I was surprised to see that there's no way to tell SSH-FS to only connect to hosts on-demand and not connect to all the hosts on startup? A per-server option would be really helpful, I guess... 
Anyone else in need of this featue?

Regards

**Comment by SchoofsKelvin** [comment]
What do you mean with auto-connect? The extension only starts the actual connection when you have a workspace folder based on it. E.g. if you have a config `test`, it'll only be activated when one of your workspace folders is `ssh://test/...`. If you're in an empty or completely unrelated workspace, it shouldn't connect.

**Comment by tpaksu** [comment]
Hi @SchoofsKelvin, 

The issue is that we have a workspace already with a saved SSH configuration, and when we open the workspace to edit some local files, VSCode automatically tries to connect to the SSH server. It'll be nice to have a setting which disables the auto-connect on workspace load and make the connection on user request. Instead, we need to create a different workspaces for our SSH connection and related (project-wise) local files.

**Comment by SchoofsKelvin** [comment]
Hmm, you're not really meant to have a SSH config as WorkspaceFolder, because vscode then expects it to work. The extension also assumes that since there's a WorkspaceFolder making use of a config, it should actually connect using the config.

I might add a `"promptBeforeConnect": true` option though, although that still means having to deal with a popup. I could make it a discardable "toast notification" at the bottom, with an explicit "Connect" button, to make it a bit more user friendly.

**Comment by tpaksu** [comment]
IMHO, ypu can also add `disableAutoConnect: true` with a default of `false` to get all these problems fixed at once :) Because we have a SSH tab at bottom of the file explorer, and that's enough to connect at will. 

And if there were two or more connections (I don't know this feature exists, maybe there will be one in the future) defined in the SSH configuration file, the `disableAutoConnect` option will have more meaning to the people who uses this extrension.

**Comment by SchoofsKelvin** [comment]
The SSH tab's "Connect as WorkspaceFolder" (or the command from the Command Palette) just adds `ssh://<name>/` as WorkspaceFolder. It doesn't actually connect. It's the same story of "extension sees a workspace folder uses a config, so connect the config"

**Comment by SchoofsKelvin** [comment]
As far as I know, I can't delay/cancel the actual connection, as vscode would show an annoying constant loading indicator. I would have to rewrite a big part of the filesystem logic to allow a fake/ghost empty root directory. A bit outside the scope of this extension right now.
